In [3]:
! pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 761 kB/s eta 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /Users/khushiyadav/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 89.3 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 2.1 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/khushiyadav/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, pandas
Successfully installed pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [4]:
import pandas as pd

In [ ]:
restaurant_data={
    'Table_no': [12,14,16],
    'Bill_amount':[1234,1235,1236],
    'Waiter_name': ['Amit', 'Chichne','Abhi']
}
df = pd.DataFrame(restaurant_data)
print(df)
print(type(df))

   Table_no  Bill_amount Waiter_name
0        12         1234        Amit
1        14         1235     Chichne
2        16         1236        Abhi
<class 'pandas.core.frame.DataFrame'>

In [7]:
print(df.values)
print(type(df.values))

[[12 1234 'Amit']
 [14 1235 'Chichne']
 [16 1236 'Abhi']]
<class 'numpy.ndarray'>

In [ ]:
price =[45,30,15,60]
price = pd.Series(price,index = ['Pizza','Burger','Pasta','Fries'])
print(price)

Pizza     45
Burger    30
Pasta     15
Fries     60
dtype: int64

In [13]:
dic = {
    'Brand': ["A","B","C"],
    'Price': ['100','200','300'],
    'In-stock':['true','false','true']

}
df = pd.DataFrame(dic)
print(df)
print(type(df))

  Brand Price In-stock
0     A   100     true
1     B   200    false
2     C   300     true
<class 'pandas.core.frame.DataFrame'>

In [16]:
df = pd.read_csv("tip.csv")
print(df)
print(type(df))

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
<class 'pandas.core.frame.DataFrame'>

In [29]:
df.head(20) # gives default 5 values from top
# df.tail()

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
15       21.58  3.92    Male     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3
17       16.29  3.71    Male     No  Sun  Dinner     3
18       16.97  3.50  Female     No  Sun  Dinner     3
19       20.65  3.35    Male     No  Sat  Dinner     3

In [ ]:
df.tail(10) #gives default 5 values from bottom

     total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [28]:
df.sample(10) # gives default single value

     total_bill   tip     sex smoker   day    time  size
167       31.71  4.50    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
120       11.69  2.31    Male     No  Thur   Lunch     2
209       12.76  2.23  Female    Yes   Sat  Dinner     2
70        12.02  1.97    Male     No   Sat  Dinner     2
217       11.59  1.50    Male    Yes   Sat  Dinner     2
187       30.46  2.00    Male    Yes   Sun  Dinner     5
45        18.29  3.00    Male     No   Sun  Dinner     2
3         23.68  3.31    Male     No   Sun  Dinner     2
183       23.17  6.50    Male    Yes   Sun  Dinner     4

In [ ]:
print(df.shape) # returns tupple 1st no of rows hota hai 2nd no of columns
print(df.columns) # isse saare columns ka name pta chal jata hai
print(type(df.columns))

(244, 7)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
<class 'pandas.core.indexes.base.Index'>

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [39]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
print(df['day'].value_counts()) # batata hai kaunse din kitne log aate hai

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
print((df['day'].unique())) # batata hai kaunse kaunse din aate hai

['Sun' 'Sat' 'Thur' 'Fri']

In [ ]:
print(df['day'].nunique()) #batata hai total kitne din aate hai

4